app:
  endpoint1 : "log:endpointFromProperties"
  timePeriod: 5000
  configs:
    name: "camel-test123"
    send-files: true
    type: "activemq"

spring:
  activemq:
    broker-url: "tcp://localhost:61616"

camel:
  component:
    kafka:
      brokers: localhost:9092