server:
    port: 8000

spring:
  activemq:
    broker-url: "tcp://localhost:61616"
    #packages:
      #trust-all: true

app:
  name: "camel-test"
  use: true

camel:
  component:
    kafka:
      brokers: localhost:9092